### ISSUE TITLE
Support for kwxsync

### ISSUE THREAD

**Issue by avri-schneider** [jenkinsci/klocwork-plugin#18]
https://developer.klocwork.com/documentation/en/insight/10-1/kwxsync

> The kwxsync command synchronizes issue status updates and comments, along with the ID of the user who made the changes, among projects that you specify. All of the updates are merged, so that identical issues in multiple projects have an identical history.
> 
> This is useful when projects share source code, as in the case of branches. Developers need to cite detected issues only once for each source file; kwxsync can then apply their changes to other projects containing the same source file. Since kwxsync can run incrementally to update only the most recent status updates and comments, you can run the tool continuously, to ensure that each developer sees an up-to-date list of issues.
> 
> The projects can be in different projects_root directories, as well as on different hosts.

When the same issue, across multiple projects, have different statuses - KW reports the status as 'Multiple', causing the KW plugin to crash.

https://github.com/cittools/klocwork-plugin/pull/17/commits/4392feac6fbd2a9bbab6452765c1fe319ecec016 provides a fix for this issue.

**Comment by jlarfors** [comment]
This was fixed with the latest pull request. Closing this issue.
