### ISSUE TITLE
ERROR: Content is not allowed in prolog

### ISSUE THREAD

**Issue by luis-garza** [jenkinsci/klocwork-plugin#59]
Hi!
I'm using Klocwork plugin in Jenkins pipelines with success, but it's failing for a specific branch build.
This is the Klocwork step which is called when I get the error:
```
klocworkQualityGateway ([
    enableCiGateway: true,
    gatewayCiConfigs: [[
        enableHTMLReporting: true,
        enabledStatuses: [
            analyze: true,
            defer: true,
            filter: true,
            fix: true,
            fixInLaterRelease: true,
            fixInNextRelease: true,
            ignore: true,
            notAProblem: true
        ],
        failUnstable: true,
        name: 'No New Issues (Any Status)',
        reportFile: "kwreport.xml",
        threshold: '1'
    ]]
])
```
The same snippet is used in the same pipeline, and it's working as is expected in other branches.

Here is error, It's extracted from a Jenkins logger under package scope `com.emenda.*` and `ALL` level:
```
Feb 17, 2020 4:19:51 PM FINE com.emenda.klocwork.KlocworkGatewayPublisher perform
[com.emenda.klocwork.KlocworkGatewayPublisher] - Performing Quality Gate
Feb 17, 2020 4:19:51 PM FINE com.emenda.klocwork.KlocworkGatewayPublisher perform
[com.emenda.klocwork.KlocworkGatewayPublisher] - Entered ci gateway
Feb 17, 2020 4:19:51 PM FINE com.emenda.klocwork.KlocworkGatewayPublisher perform
[com.emenda.klocwork.KlocworkGatewayPublisher] - [ name:No New Issues (Any Status), threshold:1, reportFile:kwreport.xml, stopBuild:false, enabledSeverities:com.emenda.klocwork.definitions.KlocworkSeverities@70526d38, enabledStatuses:com.emenda.klocwork.definitions.KlocworkStatuses@75869686, enableHTMLReporting:true ]
Feb 17, 2020 4:19:51 PM FINE com.emenda.klocwork.KlocworkGatewayPublisher perform
[com.emenda.klocwork.KlocworkGatewayPublisher] - exception thrown: Content is not allowed in prolog.
```
We are unable to reproduce it in other branches, anyone could give us some hint?

**Comment by michael-baron** [comment]
Hi Luis,

It might be down to what is reported in the xml for this branch. Either malformed, or un-escaped characters. We would most likely need to see the kwreport.xml? It might be worth raising this with Klocwork support if you don't already have a logon to the ticketing system you can submit a issue here: https://www.perforce.com/support/request-support

Best Regards,

Michael

**Comment by luis-garza** [comment]
Hi! First thanks for your quick reply.
Yes, you're right, there is something weird in the report XML.
Here is the content (I've changed the file names):
```
No such file or directory: /jenkins/workspace/foo.adoc
No such file or directory: /jenkins/workspace/bar.cpp
No such file or directory: /jenkins/workspace/baz.cpp
<?xml version="1.0" encoding="UTF-8"?>
<errorList xmlns="http://www.klocwork.com/inForce/report/1.0">
</errorList>
```
I'll report it to Klocwork support.
Thanks!

**Comment by luis-garza** [comment]
The issue could be closed.
It was caused by the git diff output file used to feed the incremental analysis, it referenced source code files that were removed during the build process.
